//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AE_VillaProject_2021.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.FavoriProducts = new HashSet<FavoriProducts>();
            this.ProductImages = new HashSet<ProductImages>();
            this.Sales = new HashSet<Sales>();
            this.Categories = new HashSet<Categories>();
        }
    
        public int ProductId { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string Metrekare { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public Nullable<double> Deposit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriProducts> FavoriProducts { get; set; }
        public virtual ProductAddresses ProductAddresses { get; set; }
        public virtual ProductDetails ProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImages> ProductImages { get; set; }
        public virtual ProductNearPlace ProductNearPlace { get; set; }
        public virtual ProductProperties ProductProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categories> Categories { get; set; }
    }
}
