//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AE_VillaProject_2021.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductProperties
    {
        public int ProductId { get; set; }
        public Nullable<bool> Tv { get; set; }
        public Nullable<bool> Klima { get; set; }
        public Nullable<bool> Wifi { get; set; }
        public Nullable<bool> Sauna { get; set; }
        public Nullable<bool> Fridge { get; set; }
        public Nullable<bool> Washer { get; set; }
        public Nullable<bool> Barbecue { get; set; }
        public Nullable<bool> Gym { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
