//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AE_VillaProject_2021.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductNearPlace
    {
        public int ProductId { get; set; }
        public string Education { get; set; }
        public string EducationDistance { get; set; }
        public string Hospital { get; set; }
        public string HospitalDistance { get; set; }
        public string TransportationType { get; set; }
        public string TransportationDisance { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
