//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AE_VillaProject_2021.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetails
    {
        public int ProductId { get; set; }
        public string RoomCount { get; set; }
        public string BathCount { get; set; }
        public string BalconyCount { get; set; }
        public string GarageCount { get; set; }
        public string PoolCount { get; set; }
        public string PersonCount { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
