//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AE_VillaProject_2021.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terms
    {
        public int TermsId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime RegisterDate { get; set; }
    }
}
