//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AE_VillaProject_2021.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetails
    {
        public int UserId { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Age { get; set; }
        public string PhoneNumber { get; set; }
        public string ImageUrl { get; set; }
        public string Address { get; set; }
        public string Tc { get; set; }
        public string PassportNumber { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
